[workspace]
members = ["app", "client"]

[package]
name = "trivia-factory"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A decentralized trivia game platform built on the Gear Protocol"
license = "MIT"
repository = "https://github.com/yourusername/trivia-factory"

[dependencies]
trivia-factory-app = { path = "app" }
sails-rs = { version = "0.4.0", features = ["gtest"] }
gstd = { version = "1.5.0", features = ["debug"] }
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false, features = [
    "derive",
] }
gmeta = { version = "1.5.0" }

[build-dependencies]
trivia-factory-app = { path = "app" }
sails-rs = { version = "0.4.0", features = ["wasm-builder"] }
sails-idl-gen = "0.4.0"

[dev-dependencies]
trivia-factory = { path = ".", features = ["wasm-binary"] }
trivia-factory-client = { path = "client" }
sails-rs = { version = "0.4.0", features = ["gtest"] }
tokio = { version = "1.39", features = ["rt", "macros", "rt-multi-thread"] }
gtest = { version = "1.5.0" }

[features]
wasm-binary = []

[[example]]
name = "create_trivia"
path = "examples/create_trivia.rs"

[[example]]
name = "play_trivia"
path = "examples/play_trivia.rs"
