[workspace]

members = ["client"]


[package]
name = "my-ping"
version = "0.1.0"
edition = "2021"

[dependencies]
my-ping-app = { path = "app" }

[build-dependencies]
my-ping-app = { path = "app" }
sails-rs = { version = "0.4.0", features = ["wasm-builder"] }
sails-idl-gen = "0.4.0"

[dev-dependencies]
my-ping = { path = ".", features = ["wasm-binary"] }
my-ping-client = { path = "client" }
sails-rs = { version = "0.4.0", features = ["gtest"] }
tokio = { version = "1.39", features = ["rt", "macros"] }

[features]
wasm-binary = []
